# run in the same folder:
# sudo docker image build ./docker --tag meetingdocker/ml:ripple2vec

FROM meetingdocker/ml:pt_0.2

# RUN conda install geoopt==0.5.0 \
# matplotlib==2.2.3 \
# networkx==2.5 \
# numpy==1.19.0 \
# scikit_learn==1.3.2 \
# scipy==1.4.1

# RUN pip install geoopt scikit_learn

# RUN conda install torch_geometric==2.3.1 
# RUN conda install pyg -c pyg
RUN pip install gensim fastdtw
